from part1 import n

CALC = [
 {"id":"deriv","s":"calc",
  "n":n("Derivative","Производная","Derivada"),
  "k":n("derivative differentiate slope tangent","производная продифференцировать наклон касательная","derivada derivar pendiente"),
  "form":r"f'(x) = \frac{d}{dx}f(x)",
  "f":[{"id":"f","l":"f(x)","t":"expr"}],
  "steps":[
   {"tex":r"f(x) = @f"},
   {"set":"d1 = diff(f, x)"},
   {"tex":r"f'(x) = @d1"},
   {"set":"d2 = diff(f, x, 2)"},
   {"tex":r"f''(x) = @d2"}]},

 {"id":"derivat","s":"calc",
  "n":n("Derivative at a point","Производная в точке","Derivada en un punto"),
  "k":n("derivative at point tangent line value","производная в точке значение касательная","derivada punto tangente"),
  "form":r"f'(x_0),\qquad y = f(x_0) + f'(x_0)(x-x_0)",
  "f":[{"id":"f","l":"f(x)","t":"expr"},{"id":"x0","l":"x_0"}],
  "steps":[
   {"tex":r"f(x) = @f"},
   {"set":"d1 = diff(f, x)"},
   {"tex":r"f'(x) = @d1"},
   {"set":"v = d1.subs(x, x0)"},
   {"set":"y0 = f.subs(x, x0)"},
   {"tex":r"f(@x0) = @y0,\qquad f'(@x0) = @v"},
   {"tex":r"y = @y0 + @v\,(x - @x0)"}]},

 {"id":"integ","s":"calc",
  "n":n("Indefinite integral","Неопределённый интеграл","Integral indefinida"),
  "k":n("integral antiderivative indefinite primitive","интеграл первообразная неопределённый","integral primitiva indefinida"),
  "form":r"\int f(x)\,dx",
  "f":[{"id":"f","l":"f(x)","t":"expr"}],
  "steps":[
   {"tex":r"\int @f \,dx"},
   {"set":"F = integrate(f, x)"},
   {"tex":r"= @F + C"}]},

 {"id":"definteg","s":"calc",
  "n":n("Definite integral","Определённый интеграл","Integral definida"),
  "k":n("definite integral area newton leibniz bounds","определённый интеграл площадь ньютон лейбниц пределы","integral definida area"),
  "form":r"\int_a^b f(x)\,dx = F(b) - F(a)",
  "f":[{"id":"f","l":"f(x)","t":"expr"},{"id":"a","l":"a"},{"id":"b","l":"b"}],
  "steps":[
   {"set":"F = integrate(f, x)"},
   {"tex":r"F(x) = \int @f\,dx = @F"},
   {"set":"Fb = F.subs(x, b)"},{"set":"Fa = F.subs(x, a)"},
   {"tex":r"F(@b) = @Fb,\qquad F(@a) = @Fa"},
   {"set":"I = Fb - Fa"},
   {"tex":r"\int_{@a}^{@b} @f\,dx = @I"},
   {"set":"If = N(I, 8)"},
   {"tex":r"\approx @If"}]},

 {"id":"limit","s":"calc",
  "n":n("Limit","Предел","Límite"),
  "k":n("limit tends approaches infinity","предел стремится бесконечность","limite tiende infinito"),
  "form":r"\lim_{x \to a} f(x)",
  "f":[{"id":"f","l":"f(x)","t":"expr"},{"id":"a","l":"a","t":"expr"}],
  "steps":[
   {"tex":r"\lim_{x \to @a} @f"},
   {"set":"L = limit(f, x, a)"},
   {"tex":r"= @L"}]},

 {"id":"taylor","s":"calc",
  "n":n("Taylor series","Ряд Тейлора","Serie de Taylor"),
  "k":n("taylor maclaurin series expansion","тейлор маклорен ряд разложение","taylor maclaurin serie"),
  "form":r"f(x) = \sum_{k=0}^{n}\frac{f^{(k)}(a)}{k!}(x-a)^k",
  "f":[{"id":"f","l":"f(x)","t":"expr"},{"id":"a","l":"a"},{"id":"n","l":"n"}],
  "need":[{"if":"n > 0","show":r"n > 0"},{"if":"n <= 12","show":r"n \leq 12"}],
  "steps":[
   {"tex":r"f(x) = @f,\qquad a = @a"},
   {"set":"T = series(f, x, a, n+1).removeO()"},
   {"tex":r"f(x) \approx @T"}]},

 {"id":"extrema","s":"calc",
  "n":n("Critical points","Точки экстремума","Puntos críticos"),
  "k":n("extremum maximum minimum critical points derivative zero","экстремум максимум минимум критические точки производная нуль","extremo maximo minimo criticos"),
  "form":r"f'(x) = 0",
  "f":[{"id":"f","l":"f(x)","t":"expr"}],
  "steps":[
   {"tex":r"f(x) = @f"},
   {"set":"d1 = diff(f, x)"},
   {"tex":r"f'(x) = @d1 = 0"},
   {"set":"pts = solve(Eq(d1, 0), x)"},
   {"tex":r"x = @pts"},
   {"set":"d2 = diff(f, x, 2)"},
   {"tex":r"f''(x) = @d2"}]},
]

LINALG = [
 {"id":"det2","s":"linalg",
  "n":n("Determinant 2×2","Определитель 2×2","Determinante 2×2"),
  "k":n("determinant two by two matrix","определитель два на два матрица","determinante dos por dos"),
  "form":r"\begin{vmatrix} a & b \\ c & d \end{vmatrix} = ad - bc",
  "f":[{"id":"a","l":"a"},{"id":"b","l":"b"},{"id":"c","l":"c"},{"id":"d","l":"d"}],
  "steps":[
   {"tex":r"\Delta = ad - bc"},
   {"set":"D = a*d - b*c"},
   {"tex":r"\Delta = (@a)(@d) - (@b)(@c) = @D"},
   {"when":"a*d - b*c != 0","steps":[
     {"tex":r"A^{-1} = \frac{1}{\Delta}\begin{pmatrix} d & -b \\ -c & a \end{pmatrix}"},
     {"set":"i11 = d/D"},{"set":"i12 = -b/D"},{"set":"i21 = -c/D"},{"set":"i22 = a/D"},
     {"tex":r"A^{-1} = \begin{pmatrix} @i11 & @i12 \\ @i21 & @i22 \end{pmatrix}"}],
    "else":[{"tex":r"\Delta = 0 \Rightarrow \nexists\, A^{-1}"}]}]},

 {"id":"det3","s":"linalg",
  "n":n("Determinant 3×3","Определитель 3×3","Determinante 3×3"),
  "k":n("determinant three by three sarrus","определитель три на три саррюс","determinante tres por tres sarrus"),
  "form":r"\begin{vmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{vmatrix}",
  "f":[{"id":"a","l":"a_{11}"},{"id":"b","l":"a_{12}"},{"id":"c","l":"a_{13}"},
       {"id":"d","l":"a_{21}"},{"id":"e","l":"a_{22}"},{"id":"f","l":"a_{23}"},
       {"id":"g","l":"a_{31}"},{"id":"h","l":"a_{32}"},{"id":"i","l":"a_{33}"}],
  "steps":[
   {"tex":r"\Delta = a_{11}(a_{22}a_{33}-a_{23}a_{32}) - a_{12}(a_{21}a_{33}-a_{23}a_{31}) + a_{13}(a_{21}a_{32}-a_{22}a_{31})"},
   {"set":"m1 = e*i - f*h"},{"set":"m2 = d*i - f*g"},{"set":"m3 = d*h - e*g"},
   {"tex":r"M_{11} = @m1,\qquad M_{12} = @m2,\qquad M_{13} = @m3"},
   {"set":"D = a*m1 - b*m2 + c*m3"},
   {"tex":r"\Delta = (@a)(@m1) - (@b)(@m2) + (@c)(@m3) = @D"}]},

 {"id":"eig2","s":"linalg",
  "n":n("Eigenvalues 2×2","Собственные значения 2×2","Valores propios 2×2"),
  "k":n("eigenvalue eigenvector characteristic polynomial spectrum","собственные значения векторы характеристический многочлен спектр","valores propios caracteristico"),
  "form":r"\det(A - \lambda I) = 0",
  "f":[{"id":"a","l":"a_{11}"},{"id":"b","l":"a_{12}"},{"id":"c","l":"a_{21}"},{"id":"d","l":"a_{22}"}],
  "steps":[
   {"tex":r"\det(A - \lambda I) = \lambda^2 - (a_{11}+a_{22})\lambda + \det A"},
   {"set":"tr = a + d"},{"set":"D = a*d - b*c"},
   {"tex":r"\operatorname{tr}A = @tr,\qquad \det A = @D"},
   {"tex":r"\lambda^2 - @tr\lambda + @D = 0"},
   {"set":"dis = tr**2 - 4*D"},
   {"tex":r"D_\lambda = (@tr)^2 - 4\cdot @D = @dis"},
   {"set":"l1 = (tr + sqrt(dis))/2"},{"set":"l2 = (tr - sqrt(dis))/2"},
   {"tex":r"\lambda_1 = @l1,\qquad \lambda_2 = @l2"}]},

 {"id":"dotprod","s":"linalg",
  "n":n("Dot product and angle","Скалярное произведение и угол","Producto escalar y ángulo"),
  "k":n("dot scalar product angle between vectors projection","скалярное произведение угол между векторами проекция","producto escalar angulo vectores"),
  "form":r"\vec a\cdot\vec b = |\vec a||\vec b|\cos\varphi",
  "f":[{"id":"ax","l":"a_x"},{"id":"ay","l":"a_y"},{"id":"az","l":"a_z"},
       {"id":"bx","l":"b_x"},{"id":"by","l":"b_y"},{"id":"bz","l":"b_z"}],
  "steps":[
   {"set":"s = ax*bx + ay*by + az*bz"},
   {"tex":r"\vec a\cdot\vec b = @ax\cdot @bx + @ay\cdot @by + @az\cdot @bz = @s"},
   {"set":"na = sqrt(ax**2 + ay**2 + az**2)"},
   {"set":"nb = sqrt(bx**2 + by**2 + bz**2)"},
   {"tex":r"|\vec a| = @na,\qquad |\vec b| = @nb"},
   {"when":"(ax**2+ay**2+az**2)*(bx**2+by**2+bz**2) > 0","steps":[
     {"set":"cf = s/(na*nb)"},
     {"tex":r"\cos\varphi = \frac{@s}{@na\cdot @nb} = @cf"},
     {"set":"phi = acos(cf)*180/pi"},
     {"set":"phif = N(phi, 6)"},
     {"tex":r"\varphi \approx @phif^\circ"}],
    "else":[{"tex":r"|\vec a||\vec b| = 0 \Rightarrow \nexists\,\varphi"}]}]},

 {"id":"crossprod","s":"linalg",
  "n":n("Cross product","Векторное произведение","Producto vectorial"),
  "k":n("cross vector product area parallelogram normal","векторное произведение площадь параллелограмма нормаль","producto vectorial area normal"),
  "form":r"\vec a\times\vec b = \begin{vmatrix} i & j & k \\ a_x & a_y & a_z \\ b_x & b_y & b_z \end{vmatrix}",
  "f":[{"id":"ax","l":"a_x"},{"id":"ay","l":"a_y"},{"id":"az","l":"a_z"},
       {"id":"bx","l":"b_x"},{"id":"by","l":"b_y"},{"id":"bz","l":"b_z"}],
  "steps":[
   {"set":"cx = ay*bz - az*by"},{"set":"cy = az*bx - ax*bz"},{"set":"cz = ax*by - ay*bx"},
   {"tex":r"\vec c = (@cx,\ @cy,\ @cz)"},
   {"set":"S = sqrt(cx**2 + cy**2 + cz**2)"},
   {"tex":r"|\vec a\times\vec b| = @S"},
   {"set":"Sf = N(S, 8)"},
   {"tex":r"\approx @Sf"}]},
]
