from part1 import n

SEQ = [
 {"id":"arith","s":"seq",
  "n":n("Arithmetic progression","Арифметическая прогрессия","Progresión aritmética"),
  "k":n("arithmetic progression difference nth term sum","арифметическая прогрессия разность член сумма","aritmetica progresion diferencia suma"),
  "form":r"a_n = a_1 + (n-1)d",
  "f":[{"id":"a1","l":"a_1"},{"id":"d","l":"d"},{"id":"n","l":"n"}],
  "need":[{"if":"n > 0","show":r"n > 0"}],
  "steps":[
   {"tex":r"a_n = a_1 + (n-1)d"},
   {"set":"an = a1 + (n-1)*d"},
   {"tex":r"a_{@n} = @a1 + (@n-1)\cdot @d = @an"},
   {"tex":r"S_n = \frac{(a_1+a_n)n}{2}"},
   {"set":"S = (a1 + an)*n/2"},
   {"tex":r"S_{@n} = \frac{(@a1 + @an)\cdot @n}{2} = @S"}]},

 {"id":"geomprog","s":"seq",
  "n":n("Geometric progression","Геометрическая прогрессия","Progresión geométrica"),
  "k":n("geometric progression ratio sum infinite","геометрическая прогрессия знаменатель сумма бесконечная","geometrica progresion razon suma"),
  "form":r"b_n = b_1 q^{\,n-1}",
  "f":[{"id":"b1","l":"b_1"},{"id":"q","l":"q"},{"id":"n","l":"n"}],
  "need":[{"if":"n > 0","show":r"n > 0"}],
  "steps":[
   {"tex":r"b_n = b_1q^{\,n-1}"},
   {"set":"bn = b1*q**(n-1)"},
   {"tex":r"b_{@n} = @b1\cdot(@q)^{@n-1} = @bn"},
   {"when":"q != 1","steps":[
     {"tex":r"S_n = b_1\frac{q^n-1}{q-1}"},
     {"set":"S = b1*(q**n - 1)/(q - 1)"},
     {"tex":r"S_{@n} = @S"}],
    "else":[{"set":"S = b1*n"},{"tex":r"q=1 \Rightarrow S_{@n} = @S"}]},
   {"when":"Abs(q) < 1","steps":[
     {"tex":r"S_\infty = \frac{b_1}{1-q}"},
     {"set":"Sinf = b1/(1-q)"},
     {"tex":r"S_\infty = @Sinf"}]}]},

 {"id":"binom","s":"seq",
  "n":n("Binomial coefficient","Биномиальный коэффициент","Coeficiente binomial"),
  "k":n("binomial coefficient combinations choose pascal","биномиальный коэффициент сочетания число выборок паскаль","binomial combinaciones"),
  "form":r"\binom{n}{k} = \frac{n!}{k!\,(n-k)!}",
  "f":[{"id":"n","l":"n"},{"id":"k","l":"k"}],
  "need":[{"if":"n >= 0","show":r"n \geq 0"},{"if":"k >= 0","show":r"k \geq 0"},{"if":"k <= n","show":r"k \leq n"}],
  "steps":[
   {"tex":r"\binom{n}{k} = \frac{n!}{k!\,(n-k)!}"},
   {"tex":r"\binom{@n}{@k} = \frac{@n!}{@k!\,(@n-@k)!}"},
   {"set":"C = binomial(n, k)"},
   {"tex":r"= @C"}]},

 {"id":"factorial","s":"seq",
  "n":n("Factorial and permutations","Факториал и перестановки","Factorial y permutaciones"),
  "k":n("factorial permutations arrangements","факториал перестановки размещения","factorial permutaciones"),
  "form":r"n! = 1\cdot2\cdots n",
  "f":[{"id":"n","l":"n"},{"id":"k","l":"k"}],
  "need":[{"if":"n >= 0","show":r"n \geq 0"},{"if":"k >= 0","show":r"k \geq 0"},{"if":"k <= n","show":r"k \leq n"}],
  "steps":[
   {"set":"F = factorial(n)"},
   {"tex":r"@n! = @F"},
   {"tex":r"A_n^k = \frac{n!}{(n-k)!}"},
   {"set":"A = factorial(n)/factorial(n-k)"},
   {"tex":r"A_{@n}^{@k} = \frac{@n!}{(@n-@k)!} = @A"}]},
]

TRIG = [
 {"id":"trigval","s":"trig",
  "n":n("Sine, cosine, tangent of an angle","Синус, косинус, тангенс угла","Seno, coseno, tangente"),
  "k":n("sine cosine tangent angle degrees radians","синус косинус тангенс угол градусы радианы","seno coseno tangente angulo grados"),
  "form":r"\sin\alpha,\ \cos\alpha,\ \tan\alpha",
  "f":[{"id":"deg","l":"\\alpha^\\circ"}],
  "steps":[
   {"tex":r"\alpha = @deg^\circ = \frac{@deg\pi}{180}"},
   {"set":"r = deg*pi/180"},
   {"tex":r"\alpha = @r"},
   {"set":"s = sin(r)"},{"set":"c = cos(r)"},
   {"tex":r"\sin\alpha = @s,\qquad \cos\alpha = @c"},
   {"when":"cos(deg*pi/180) != 0","steps":[
     {"set":"t = tan(r)"},
     {"tex":r"\tan\alpha = @t"}],
    "else":[{"tex":r"\cos\alpha = 0 \Rightarrow \tan\alpha \text{ —}\ \nexists"}]},
   {"set":"sf = N(s, 8)"},{"set":"cf = N(c, 8)"},
   {"tex":r"\approx @sf,\qquad @cf"}]},

 {"id":"pythag","s":"trig",
  "n":n("Pythagorean theorem","Теорема Пифагора","Teorema de Pitágoras"),
  "k":n("pythagoras hypotenuse leg right triangle","пифагор гипотенуза катет прямоугольный треугольник","pitagoras hipotenusa cateto"),
  "form":r"a^2 + b^2 = c^2",
  "f":[{"id":"a","l":"a"},{"id":"b","l":"b"}],
  "need":[{"if":"a > 0","show":r"a > 0"},{"if":"b > 0","show":r"b > 0"}],
  "steps":[
   {"tex":r"c = \sqrt{a^2+b^2}"},
   {"set":"c = sqrt(a**2 + b**2)"},
   {"tex":r"c = \sqrt{(@a)^2 + (@b)^2} = @c"},
   {"set":"cf = N(c, 8)"},
   {"tex":r"\approx @cf"}]},

 {"id":"cosrule","s":"trig",
  "n":n("Law of cosines","Теорема косинусов","Teorema del coseno"),
  "k":n("law of cosines triangle side angle","теорема косинусов треугольник сторона угол","teorema coseno triangulo"),
  "form":r"c^2 = a^2 + b^2 - 2ab\cos\gamma",
  "f":[{"id":"a","l":"a"},{"id":"b","l":"b"},{"id":"g","l":"\\gamma^\\circ"}],
  "need":[{"if":"a > 0","show":r"a > 0"},{"if":"b > 0","show":r"b > 0"},
          {"if":"g > 0","show":r"\gamma > 0"},{"if":"g < 180","show":r"\gamma < 180^\circ"}],
  "steps":[
   {"tex":r"c^2 = a^2 + b^2 - 2ab\cos\gamma"},
   {"set":"r = g*pi/180"},
   {"set":"c2 = a**2 + b**2 - 2*a*b*cos(r)"},
   {"tex":r"c^2 = (@a)^2 + (@b)^2 - 2\cdot @a\cdot @b\cos @g^\circ = @c2"},
   {"set":"c = sqrt(c2)"},
   {"tex":r"c = @c"},
   {"set":"cf = N(c, 8)"},
   {"tex":r"\approx @cf"}]},

 {"id":"sinrule","s":"trig",
  "n":n("Law of sines","Теорема синусов","Teorema del seno"),
  "k":n("law of sines triangle circumradius","теорема синусов треугольник описанная окружность","teorema seno triangulo"),
  "form":r"\frac{a}{\sin\alpha} = \frac{b}{\sin\beta} = 2R",
  "f":[{"id":"a","l":"a"},{"id":"al","l":"\\alpha^\\circ"},{"id":"be","l":"\\beta^\\circ"}],
  "need":[{"if":"a > 0","show":r"a > 0"},{"if":"al > 0","show":r"\alpha > 0"},
          {"if":"al < 180","show":r"\alpha < 180^\circ"},{"if":"be > 0","show":r"\beta > 0"},
          {"if":"be < 180","show":r"\beta < 180^\circ"},{"if":"al + be < 180","show":r"\alpha + \beta < 180^\circ"}],
  "steps":[
   {"set":"ra = al*pi/180"},{"set":"rb = be*pi/180"},
   {"set":"R = a/(2*sin(ra))"},
   {"tex":r"2R = \frac{a}{\sin\alpha} \Rightarrow R = @R"},
   {"set":"b = 2*R*sin(rb)"},
   {"tex":r"b = 2R\sin\beta = @b"},
   {"set":"ga = 180 - al - be"},
   {"tex":r"\gamma = 180^\circ - @al^\circ - @be^\circ = @ga^\circ"},
   {"set":"bf = N(b, 8)"},
   {"tex":r"b \approx @bf"}]},
]
