from part1 import n

GEOM = [
 {"id":"circle","s":"geom",
  "n":n("Circle","Окружность и круг","Círculo"),
  "k":n("circle area circumference radius diameter","окружность круг площадь длина радиус диаметр","circulo area circunferencia radio"),
  "form":r"L = 2\pi R,\qquad S = \pi R^2",
  "f":[{"id":"R","l":"R"}],
  "need":[{"if":"R > 0","show":r"R > 0"}],
  "steps":[
   {"set":"L = 2*pi*R"},{"set":"S = pi*R**2"},
   {"tex":r"L = 2\pi\cdot @R = @L"},
   {"tex":r"S = \pi(@R)^2 = @S"},
   {"set":"Lf = N(L, 8)"},{"set":"Sf = N(S, 8)"},
   {"tex":r"\approx @Lf,\qquad @Sf"}]},

 {"id":"triarea","s":"geom",
  "n":n("Triangle area","Площадь треугольника","Área del triángulo"),
  "k":n("triangle area heron sides semiperimeter","площадь треугольника герон стороны полупериметр","area triangulo heron"),
  "form":r"S = \sqrt{p(p-a)(p-b)(p-c)}",
  "f":[{"id":"a","l":"a"},{"id":"b","l":"b"},{"id":"c","l":"c"}],
  "need":[{"if":"a > 0","show":r"a > 0"},{"if":"b > 0","show":r"b > 0"},{"if":"c > 0","show":r"c > 0"},
          {"if":"a + b > c","show":r"a + b > c"},{"if":"a + c > b","show":r"a + c > b"},{"if":"b + c > a","show":r"b + c > a"}],
  "steps":[
   {"set":"p = (a + b + c)/2"},
   {"tex":r"p = \frac{@a + @b + @c}{2} = @p"},
   {"set":"S = sqrt(p*(p-a)*(p-b)*(p-c))"},
   {"tex":r"S = \sqrt{@p(@p-@a)(@p-@b)(@p-@c)} = @S"},
   {"set":"Sf = N(S, 8)"},
   {"tex":r"\approx @Sf"}]},

 {"id":"sphere","s":"geom",
  "n":n("Sphere and ball","Сфера и шар","Esfera y bola"),
  "k":n("sphere ball volume surface radius","сфера шар объём площадь поверхности радиус","esfera volumen superficie"),
  "form":r"S = 4\pi R^2,\qquad V = \tfrac{4}{3}\pi R^3",
  "f":[{"id":"R","l":"R"}],
  "need":[{"if":"R > 0","show":r"R > 0"}],
  "steps":[
   {"set":"S = 4*pi*R**2"},{"set":"V = 4*pi*R**3/3"},
   {"tex":r"S = 4\pi(@R)^2 = @S"},
   {"tex":r"V = \tfrac{4}{3}\pi(@R)^3 = @V"},
   {"set":"Sf = N(S, 8)"},{"set":"Vf = N(V, 8)"},
   {"tex":r"\approx @Sf,\qquad @Vf"}]},

 {"id":"dist2","s":"geom",
  "n":n("Distance and midpoint","Расстояние и середина отрезка","Distancia y punto medio"),
  "k":n("distance between points midpoint segment coordinates","расстояние между точками середина отрезка координаты","distancia puntos medio segmento"),
  "form":r"d = \sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}",
  "f":[{"id":"x1","l":"x_1"},{"id":"y1","l":"y_1"},{"id":"x2","l":"x_2"},{"id":"y2","l":"y_2"}],
  "steps":[
   {"set":"d = sqrt((x2-x1)**2 + (y2-y1)**2)"},
   {"tex":r"d = \sqrt{(@x2-@x1)^2 + (@y2-@y1)^2} = @d"},
   {"set":"mx = (x1+x2)/2"},{"set":"my = (y1+y2)/2"},
   {"tex":r"M = \left(@mx,\ @my\right)"},
   {"set":"df = N(d, 8)"},
   {"tex":r"d \approx @df"}]},

 {"id":"lineth","s":"geom",
  "n":n("Line through two points","Прямая через две точки","Recta por dos puntos"),
  "k":n("line through two points slope equation","прямая через две точки уравнение угловой коэффициент","recta dos puntos pendiente"),
  "form":r"y = kx + b",
  "f":[{"id":"x1","l":"x_1"},{"id":"y1","l":"y_1"},{"id":"x2","l":"x_2"},{"id":"y2","l":"y_2"}],
  "need":[{"if":"x1 != x2","show":r"x_1 \neq x_2"}],
  "steps":[
   {"set":"k = (y2-y1)/(x2-x1)"},
   {"tex":r"k = \frac{@y2 - @y1}{@x2 - @x1} = @k"},
   {"set":"b = y1 - k*x1"},
   {"tex":r"b = @y1 - @k\cdot @x1 = @b"},
   {"tex":r"y = @k\,x + @b"}]},
]

PROB = [
 {"id":"variance","s":"prob",
  "n":n("Mean and variance","Среднее и дисперсия","Media y varianza"),
  "k":n("variance standard deviation mean average sample dispersion",
        "дисперсия среднее квадратичное отклонение выборка разброс",
        "varianza desviacion media muestra"),
  "form":r"D = \frac{1}{n}\sum (x_i - \bar x)^2",
  "f":[{"id":"xs","l":"x_i","t":"list"}],
  "steps":[
   {"tex":r"x = (@xs)"},
   {"set":"nn = len(xs)"},
   {"set":"m = sum(xs)/len(xs)"},
   {"tex":r"\bar x = \frac{1}{@nn}\sum x_i = @m"},
   {"set":"D = sum([(v - m)**2 for v in xs])/len(xs)"},
   {"tex":r"D = \frac{1}{@nn}\sum (x_i - @m)^2 = @D"},
   {"set":"s = sqrt(D)"},
   {"tex":r"\sigma = \sqrt{D} = @s"},
   {"set":"Ds = sum([(v - m)**2 for v in xs])/(len(xs)-1)"},
   {"tex":r"s^2 = \frac{1}{n-1}\sum (x_i - \bar x)^2 = @Ds"},
   {"set":"mf = N(m, 8)"},{"set":"Df = N(D, 8)"},{"set":"sf = N(s, 8)"},
   {"tex":r"\approx \bar x = @mf,\quad D = @Df,\quad \sigma = @sf"}]},

 {"id":"bayes","s":"prob",
  "n":n("Bayes' theorem","Формула Байеса","Teorema de Bayes"),
  "k":n("bayes conditional probability posterior prior","байес условная вероятность апостериорная","bayes probabilidad condicional"),
  "form":r"P(A\mid B) = \frac{P(B\mid A)P(A)}{P(B)}",
  "f":[{"id":"pa","l":"P(A)"},{"id":"pba","l":"P(B\\mid A)"},{"id":"pbna","l":"P(B\\mid \\bar A)"}],
  "need":[{"if":"pa >= 0","show":r"P(A) \geq 0"},{"if":"pa <= 1","show":r"P(A) \leq 1"},
          {"if":"pba >= 0","show":r"P(B\mid A) \geq 0"},{"if":"pba <= 1","show":r"P(B\mid A) \leq 1"},
          {"if":"pbna >= 0","show":r"P(B\mid \bar A) \geq 0"},{"if":"pbna <= 1","show":r"P(B\mid \bar A) \leq 1"}],
  "steps":[
   {"tex":r"P(B) = P(B\mid A)P(A) + P(B\mid \bar A)P(\bar A)"},
   {"set":"pb = pba*pa + pbna*(1-pa)"},
   {"tex":r"P(B) = @pba\cdot @pa + @pbna\cdot(1-@pa) = @pb"},
   {"when":"pba*pa + pbna*(1-pa) > 0","steps":[
     {"set":"post = pba*pa/pb"},
     {"tex":r"P(A\mid B) = \frac{@pba\cdot @pa}{@pb} = @post"},
     {"set":"pf = N(post, 8)"},
     {"tex":r"\approx @pf"}],
    "else":[{"tex":r"P(B) = 0 \Rightarrow \nexists\, P(A\mid B)"}]}]},

 {"id":"binomdist","s":"prob",
  "n":n("Binomial distribution","Биномиальное распределение","Distribución binomial"),
  "k":n("binomial distribution bernoulli trials success probability",
        "биномиальное распределение бернулли испытания успех вероятность",
        "binomial bernoulli ensayos exito"),
  "form":r"P(X=k) = \binom{n}{k}p^k(1-p)^{n-k}",
  "f":[{"id":"n","l":"n"},{"id":"k","l":"k"},{"id":"p","l":"p"}],
  "need":[{"if":"n > 0","show":r"n > 0"},{"if":"k >= 0","show":r"k \geq 0"},{"if":"k <= n","show":r"k \leq n"},
          {"if":"p >= 0","show":r"p \geq 0"},{"if":"p <= 1","show":r"p \leq 1"}],
  "steps":[
   {"set":"C = binomial(n, k)"},
   {"tex":r"\binom{@n}{@k} = @C"},
   {"set":"P = C*p**k*(1-p)**(n-k)"},
   {"tex":r"P(X=@k) = @C\cdot(@p)^{@k}(1-@p)^{@n-@k} = @P"},
   {"set":"E = n*p"},{"set":"D = n*p*(1-p)"},
   {"tex":r"\mathbb{E}X = np = @E,\qquad DX = np(1-p) = @D"},
   {"set":"Pf = N(P, 8)"},
   {"tex":r"P \approx @Pf"}]},

 {"id":"normal","s":"prob",
  "n":n("Normal distribution","Нормальное распределение","Distribución normal"),
  "k":n("normal gauss distribution density sigma mu z score",
        "нормальное распределение гаусс плотность сигма мю",
        "normal gauss densidad sigma"),
  "form":r"f(x) = \frac{1}{\sigma\sqrt{2\pi}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}",
  "f":[{"id":"mu","l":"\\mu"},{"id":"sg","l":"\\sigma"},{"id":"x","l":"x"}],
  "need":[{"if":"sg > 0","show":r"\sigma > 0"}],
  "steps":[
   {"set":"z = (x - mu)/sg"},
   {"tex":r"z = \frac{@x - @mu}{@sg} = @z"},
   {"set":"fx = exp(-z**2/2)/(sg*sqrt(2*pi))"},
   {"tex":r"f(@x) = \frac{1}{@sg\sqrt{2\pi}}e^{-\frac{@z^2}{2}} = @fx"},
   {"set":"ff = N(fx, 8)"},{"set":"zf = N(z, 8)"},
   {"tex":r"z \approx @zf,\qquad f(x) \approx @ff"}]},

 {"id":"lsq","s":"prob",
  "n":n("Least squares line","Метод наименьших квадратов","Mínimos cuadrados"),
  "k":n("least squares regression line fit slope intercept",
        "наименьшие квадраты регрессия прямая приближение",
        "minimos cuadrados regresion recta"),
  "form":r"y = kx + b,\qquad k = \frac{\overline{xy} - \bar x\bar y}{\overline{x^2} - \bar x^2}",
  "f":[{"id":"xs","l":"x_i","t":"list"},{"id":"ys","l":"y_i","t":"list"}],
  "need":[{"if":"len(xs) == len(ys)","show":r"|x| = |y|"},{"if":"len(xs) > 1","show":r"n > 1"}],
  "steps":[
   {"set":"nn = len(xs)"},
   {"set":"mx = sum(xs)/len(xs)"},{"set":"my = sum(ys)/len(ys)"},
   {"tex":r"\bar x = @mx,\qquad \bar y = @my"},
   {"set":"mxy = sum([xs[i]*ys[i] for i in range(len(xs))])/len(xs)"},
   {"set":"mx2 = sum([v**2 for v in xs])/len(xs)"},
   {"tex":r"\overline{xy} = @mxy,\qquad \overline{x^2} = @mx2"},
   {"when":"sum([v**2 for v in xs])/len(xs) - (sum(xs)/len(xs))**2 != 0","steps":[
     {"set":"k = (mxy - mx*my)/(mx2 - mx**2)"},
     {"set":"b = my - k*mx"},
     {"tex":r"k = \frac{@mxy - @mx\cdot @my}{@mx2 - (@mx)^2} = @k"},
     {"tex":r"b = @my - @k\cdot @mx = @b"},
     {"tex":r"y = @k\,x + @b"}],
    "else":[{"tex":r"\overline{x^2} - \bar x^2 = 0 \Rightarrow \nexists\, k"}]}]},
]
