from part1 import n

MORE_CALC = [
 {"id":"partial","s":"calc",
  "n":n("Partial derivatives and gradient","Частные производные и градиент","Derivadas parciales y gradiente"),
  "k":n("partial derivative gradient nabla multivariable","частная производная градиент набла нескольких переменных","parcial gradiente nabla"),
  "form":r"\nabla f = \left(\frac{\partial f}{\partial x},\ \frac{\partial f}{\partial y}\right)",
  "f":[{"id":"f","l":"f(x,y)","t":"expr"}],
  "try":{"f":"x^2 y + y^3"},
  "steps":[
   {"tex":r"f(x,y) = @f"},
   {"set":"fx = diff(f, x)"},{"set":"fy = diff(f, y)"},
   {"tex":r"\frac{\partial f}{\partial x} = @fx,\qquad \frac{\partial f}{\partial y} = @fy"},
   {"set":"fxx = diff(f, x, 2)"},{"set":"fyy = diff(f, y, 2)"},{"set":"fxy = diff(f, x, 1, y, 1)"},
   {"tex":r"H = \begin{pmatrix} @fxx & @fxy \\ @fxy & @fyy \end{pmatrix}"}]},

 {"id":"ode1","s":"calc",
  "n":n("First order ODE","Дифференциальное уравнение первого порядка","EDO de primer orden"),
  "k":n("differential equation first order separable ode","дифференциальное уравнение первого порядка разделяющиеся","ecuacion diferencial primer orden"),
  "form":r"y' = f(x,y)",
  "f":[{"id":"f","l":"f(x,y)","t":"expr"}],
  "try":{"f":"-2*y"},
  "steps":[
   {"tex":r"y' = @f"},
   {"set":"sol = dsolve(Eq(Derivative(Function('y')(x), x), f.subs(y, Function('y')(x))), Function('y')(x))"},
   {"tex":r"@sol"}]},

 {"id":"ode2","s":"calc",
  "n":n("Linear ODE second order","Линейное уравнение второго порядка","EDO lineal de segundo orden"),
  "k":n("second order linear homogeneous characteristic equation ode","второго порядка линейное однородное характеристическое уравнение","segundo orden lineal caracteristica"),
  "form":r"y'' + py' + qy = 0",
  "f":[{"id":"p","l":"p"},{"id":"q","l":"q"}],
  "try":{"p":"-3","q":"2"},
  "steps":[
   {"set":"eq = Symbol(chr(92)+'lambda')**2 + p*Symbol(chr(92)+'lambda') + q"},
   {"tex":r"y'' + \left(@p\right)y' + \left(@q\right)y = 0"},
   {"tex":r"@eq = 0"},
   {"set":"D = p**2 - 4*q"},
   {"tex":r"D = (@p)^2 - 4\cdot @q = @D"},
   {"set":"ls = solve(Eq(t**2 + p*t + q, 0), t)"},
   {"tex":r"\lambda = @ls"},
   {"when":"D > 0","steps":[
     {"set":"l1 = ls[0]"},{"set":"l2 = ls[1]"},
     {"set":"e1 = exp(l1*x)"},{"set":"e2 = exp(l2*x)"},
     {"tex":r"y = C_1\,@e1 + C_2\,@e2"}],
    "else":[{"when":"D = 0","steps":[
      {"set":"l1 = ls[0]"},
      {"set":"e1 = exp(l1*x)"},
      {"tex":r"y = (C_1 + C_2 x)\,@e1"}],
     "else":[
      {"set":"al = -p/2"},{"set":"be = sqrt(-D)/2"},
      {"tex":r"y = e^{@al x}\left(C_1\cos @be x + C_2\sin @be x\right)"}]}]}]},

 {"id":"dblint","s":"calc",
  "n":n("Double integral","Двойной интеграл","Integral doble"),
  "k":n("double integral area region iterated","двойной интеграл площадь область повторный","integral doble area region"),
  "form":r"\iint_D f(x,y)\,dx\,dy",
  "f":[{"id":"f","l":"f(x,y)","t":"expr"},{"id":"x1","l":"x_1"},{"id":"x2","l":"x_2"},
       {"id":"y1","l":"y_1"},{"id":"y2","l":"y_2"}],
  "try":{"f":"x*y","x1":"0","x2":"1","y1":"0","y2":"2"},
  "steps":[
   {"set":"inner = integrate(f, (y, y1, y2))"},
   {"tex":r"\int_{@y1}^{@y2} @f \,dy = @inner"},
   {"set":"I = integrate(inner, (x, x1, x2))"},
   {"tex":r"\int_{@x1}^{@x2}\!\!\int_{@y1}^{@y2} @f \,dy\,dx = @I"},
   {"set":"If = N(I,8)"},
   {"tex":r"\approx @If"}]},

 {"id":"arclen","s":"calc",
  "n":n("Arc length","Длина дуги","Longitud de arco"),
  "k":n("arc length curve integral","длина дуги кривой интеграл","longitud arco curva"),
  "form":r"L = \int_a^b \sqrt{1 + (f')^2}\,dx",
  "f":[{"id":"f","l":"f(x)","t":"expr"},{"id":"a","l":"a"},{"id":"b","l":"b"}],
  "try":{"f":"x^2","a":"0","b":"1"},
  "steps":[
   {"set":"d1 = diff(f, x)"},
   {"tex":r"f'(x) = @d1"},
   {"set":"L = integrate(sqrt(1 + d1**2), (x, a, b))"},
   {"tex":r"L = \int_{@a}^{@b}\sqrt{1 + \left(@d1\right)^2}\,dx = @L"},
   {"set":"Lf = N(L,8)"},
   {"tex":r"\approx @Lf"}]},

 {"id":"series","s":"calc",
  "n":n("Series sum","Сумма ряда","Suma de una serie"),
  "k":n("series sum convergence infinite","ряд сумма сходимость бесконечный","serie suma convergencia"),
  "form":r"\sum_{k=1}^{\infty} a_k",
  "f":[{"id":"a","l":"a_k","t":"expr"}],
  "try":{"a":"1/k^2"},
  "steps":[
   {"set":"k = Symbol('k')"},
   {"tex":r"\sum_{k=1}^{\infty} @a"},
   {"set":"S = summation(a, (Symbol('k'), 1, oo))"},
   {"tex":r"= @S"},
   {"set":"Sf = N(S,8)"},
   {"tex":r"\approx @Sf"}]},
]

MORE_LIN = [
 {"id":"matmul","s":"linalg",
  "n":n("Matrix product 2×2","Произведение матриц 2×2","Producto de matrices 2×2"),
  "k":n("matrix multiplication product two by two","умножение матриц произведение два на два","multiplicacion matrices producto"),
  "form":r"C = AB",
  "f":[{"id":"a","l":"a_{11}"},{"id":"b","l":"a_{12}"},{"id":"c","l":"a_{21}"},{"id":"d","l":"a_{22}"},
       {"id":"e","l":"b_{11}"},{"id":"f","l":"b_{12}"},{"id":"g","l":"b_{21}"},{"id":"h","l":"b_{22}"}],
  "try":{"a":"1","b":"2","c":"3","d":"4","e":"0","f":"1","g":"1","h":"0"},
  "steps":[
   {"set":"c11 = a*e + b*g"},{"set":"c12 = a*f + b*h"},
   {"set":"c21 = c*e + d*g"},{"set":"c22 = c*f + d*h"},
   {"tex":r"C = \begin{pmatrix} @c11 & @c12 \\ @c21 & @c22 \end{pmatrix}"},
   {"set":"D = (a*d-b*c)*(e*h-f*g)"},
   {"tex":r"\det C = \det A\cdot\det B = @D"}]},

 {"id":"gauss3","s":"linalg",
  "n":n("System of three equations","Система трёх уравнений","Sistema de tres ecuaciones"),
  "k":n("system three equations gauss cramer solve","система трёх уравнений гаусс крамер решить","sistema tres ecuaciones gauss"),
  "form":r"\begin{cases} a_1x+b_1y+c_1z=d_1 \\ a_2x+b_2y+c_2z=d_2 \\ a_3x+b_3y+c_3z=d_3 \end{cases}",
  "f":[{"id":"a1","l":"a_1"},{"id":"b1","l":"b_1"},{"id":"c1","l":"c_1"},{"id":"d1","l":"d_1"},
       {"id":"a2","l":"a_2"},{"id":"b2","l":"b_2"},{"id":"c2","l":"c_2"},{"id":"d2","l":"d_2"},
       {"id":"a3","l":"a_3"},{"id":"b3","l":"b_3"},{"id":"c3","l":"c_3"},{"id":"d3","l":"d_3"}],
  "try":{"a1":"1","b1":"1","c1":"1","d1":"6","a2":"0","b2":"2","c2":"1","d2":"7",
         "a3":"2","b3":"0","c3":"1","d3":"5"},
  "steps":[
   {"set":"M = Matrix([[a1,b1,c1],[a2,b2,c2],[a3,b3,c3]])"},
   {"set":"D = M.det()"},
   {"tex":r"\Delta = @D"},
   {"when":"Matrix([[a1,b1,c1],[a2,b2,c2],[a3,b3,c3]]).det() != 0","steps":[
     {"set":"sol = M.solve(Matrix([d1,d2,d3]))"},
     {"tex":r"\begin{pmatrix} x \\ y \\ z \end{pmatrix} = @sol"}],
    "else":[{"tex":r"\Delta = 0 \Rightarrow \nexists!\,(x,y,z)"}]}]},

 {"id":"rank","s":"linalg",
  "n":n("Rank and inverse 3×3","Ранг и обратная 3×3","Rango e inversa 3×3"),
  "k":n("rank inverse matrix three by three singular","ранг обратная матрица три на три вырожденная","rango inversa matriz"),
  "form":r"\operatorname{rank}A,\qquad A^{-1}",
  "f":[{"id":"a","l":"a_{11}"},{"id":"b","l":"a_{12}"},{"id":"c","l":"a_{13}"},
       {"id":"d","l":"a_{21}"},{"id":"e","l":"a_{22}"},{"id":"f","l":"a_{23}"},
       {"id":"g","l":"a_{31}"},{"id":"h","l":"a_{32}"},{"id":"i","l":"a_{33}"}],
  "try":{"a":"1","b":"2","c":"3","d":"0","e":"1","f":"4","g":"5","h":"6","i":"0"},
  "steps":[
   {"set":"M = Matrix([[a,b,c],[d,e,f],[g,h,i]])"},
   {"set":"r = M.rank()"},
   {"tex":r"\operatorname{rank}A = @r"},
   {"set":"D = M.det()"},
   {"tex":r"\det A = @D"},
   {"when":"Matrix([[a,b,c],[d,e,f],[g,h,i]]).det() != 0","steps":[
     {"set":"Inv = M.inv()"},
     {"tex":r"A^{-1} = @Inv"}],
    "else":[{"tex":r"\det A = 0 \Rightarrow \nexists\,A^{-1}"}]}]},
]

MORE_PROB = [
 {"id":"poisson","s":"prob",
  "n":n("Poisson distribution","Распределение Пуассона","Distribución de Poisson"),
  "k":n("poisson distribution rare events lambda","пуассон распределение редкие события лямбда","poisson eventos raros"),
  "form":r"P(X=k) = \frac{\lambda^k}{k!}e^{-\lambda}",
  "f":[{"id":"lam","l":"\\lambda"},{"id":"k","l":"k"}],
  "need":[{"if":"lam > 0","show":r"\lambda > 0"},{"if":"k >= 0","show":r"k \geq 0"}],
  "try":{"lam":"3","k":"2"},
  "steps":[
   {"set":"P = lam**k*exp(-lam)/factorial(k)"},
   {"tex":r"P(X=@k) = \frac{@lam^{@k}}{@k!}e^{-@lam} = @P"},
   {"set":"Pf = N(P,8)"},
   {"tex":r"\approx @Pf"},
   {"tex":r"\mathbb{E}X = DX = @lam"}]},

 {"id":"corr","s":"prob",
  "n":n("Covariance and correlation","Ковариация и корреляция","Covarianza y correlación"),
  "k":n("covariance correlation pearson coefficient linear","ковариация корреляция пирсон коэффициент связь","covarianza correlacion pearson"),
  "form":r"r = \frac{\operatorname{cov}(x,y)}{\sigma_x\sigma_y}",
  "f":[{"id":"xs","l":"x_i","t":"list"},{"id":"ys","l":"y_i","t":"list"}],
  "need":[{"if":"len(xs) == len(ys)","show":r"|x| = |y|"},{"if":"len(xs) > 1","show":r"n > 1"}],
  "try":{"xs":"1,2,3,4,5","ys":"2,4,5,4,5"},
  "steps":[
   {"set":"mx = sum(xs)/len(xs)"},{"set":"my = sum(ys)/len(ys)"},
   {"tex":r"\bar x = @mx,\qquad \bar y = @my"},
   {"set":"cov = sum([(xs[i]-mx)*(ys[i]-my) for i in range(len(xs))])/len(xs)"},
   {"tex":r"\operatorname{cov}(x,y) = @cov"},
   {"set":"sx = sqrt(sum([(v-mx)**2 for v in xs])/len(xs))"},
   {"set":"sy = sqrt(sum([(v-my)**2 for v in ys])/len(ys))"},
   {"tex":r"\sigma_x = @sx,\qquad \sigma_y = @sy"},
   {"when":"sum([(v-sum(xs)/len(xs))**2 for v in xs])*sum([(v-sum(ys)/len(ys))**2 for v in ys]) > 0","steps":[
     {"set":"r = cov/(sx*sy)"},
     {"set":"rf = N(r,8)"},
     {"tex":r"r = @r \approx @rf"}],
    "else":[{"tex":r"\sigma_x\sigma_y = 0 \Rightarrow \nexists\, r"}]}]},
]

NUMER = [
 {"id":"newton","s":"num",
  "n":n("Newton's method","Метод Ньютона","Método de Newton"),
  "k":n("newton method root iteration tangent numerical","ньютон метод касательных корень итерация численный","newton raiz iteracion"),
  "form":r"x_{k+1} = x_k - \frac{f(x_k)}{f'(x_k)}",
  "f":[{"id":"f","l":"f(x)","t":"expr"},{"id":"x0","l":"x_0"},{"id":"m","l":"m"}],
  "need":[{"if":"m > 0","show":r"m > 0"},{"if":"m <= 8","show":r"m \leq 8"}],
  "try":{"f":"x^2 - 2","x0":"1","m":"4"},
  "steps":[
   {"set":"d1 = diff(f, x)"},
   {"tex":r"f(x) = @f,\qquad f'(x) = @d1"},
   {"set":"xs = [x0]"},
   {"set":"tmp = [xs.append(N(xs[-1] - f.subs(x, xs[-1])/d1.subs(x, xs[-1]), 12)) for i in range(m)]"},
   {"tex":r"x_0 = @x0"},
   {"set":"last = xs[-1]"},
   {"tex":r"x_1,\dots,x_{@m} = @xs"},
   {"tex":r"x \approx @last"}]},

 {"id":"simpson","s":"num",
  "n":n("Numerical integration","Численное интегрирование","Integración numérica"),
  "k":n("simpson trapezoid numerical integration quadrature","симпсон трапеция численное интегрирование квадратура","simpson trapecio numerica"),
  "form":r"\int_a^b f\,dx \approx \frac{h}{3}\left(f_0 + 4f_1 + 2f_2 + \dots + f_n\right)",
  "f":[{"id":"f","l":"f(x)","t":"expr"},{"id":"a","l":"a"},{"id":"b","l":"b"},{"id":"nn","l":"n"}],
  "need":[{"if":"nn > 0","show":r"n > 0"},{"if":"nn % 2 == 0","show":r"2 \mid n"},{"if":"nn <= 40","show":r"n \leq 40"}],
  "try":{"f":"1/(1+x^2)","a":"0","b":"1","nn":"4"},
  "steps":[
   {"set":"h = (b - a)/nn"},
   {"tex":r"h = \frac{@b - @a}{@nn} = @h"},
   {"set":"pts = [N(f.subs(x, a + i*h), 12) for i in range(nn+1)]"},
   {"tex":r"f_i = @pts"},
   {"set":"S = N(h/3*(pts[0] + pts[-1] + 4*sum([pts[i] for i in range(1,nn,2)]) + 2*sum([pts[i] for i in range(2,nn,2)])), 12)"},
   {"tex":r"\int_{@a}^{@b} f\,dx \approx @S"},
   {"set":"exact = N(integrate(f, (x, a, b)), 12)"},
   {"tex":r"\text{точно: } @exact"}]},
]
